stages:
  - build

variables:
  DEB_PACKAGE: loodsen-aa-profiles
  DEB_VERSION: 2024.11.21-1

build-deb:
  stage: build
  tags:
    - k8s
  id_tokens:
    VAULT_JWT_TOKEN:
      aud: https://git02.loodsen.ru
  before_script:
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt_dkb/login role=dkb_s3-infosec_main jwt=$VAULT_JWT_TOKEN)"
#   - echo "$(vault kv get -field=registry_pass kv/DKB/s3-infosec/main/build)" > /kaniko/.docker/config.json
  script:
    - apt-get update -qq
    - apt-get install dpkg debconf debhelper lintian
    - git clone https://git02.loodsen.ru/sec-public/apparmor 
    - chmod 0755 "${CI_PROJECT_DIR}/$DEB_PACKAGE/DEBIAN/postinst"
    - fakeroot dpkg-deb --build $DEB_PACKAGE
    - mv $DEB_PACKAGE.deb ${DEB_PACKAGE}_${DEB_VERSION}_all.deb
  artifacts:
    paths:
      - ${DEB_PACKAGE}_${DEB_VERSION}_amd64.deb
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_REF_NAME == "main"'
      when: manual
    - if: '$CI_COMMIT_REF_PROTECTED == "true"'
      when: manual
