image: docker:latest

stages:
  - build

variables:
  DEB_PACKAGE: my-package
  DEB_VERSION: 1.0

build-deb:
  stage: build
  script:
    - apt-get update -qq
    - apt-get install -y devscripts debhelper
    - mkdir -p debian
    - cp -r packaging/debian/* debian/
    - sed -i "s/VERSION/${DEB_VERSION}/g" debian/changelog
    - dpkg-buildpackage -us -uc -b
  artifacts:
    paths:
      - ${DEB_PACKAGE}_${DEB_VERSION}_amd64.deb