# The method of connecting the apparmor profile to kybernetes

apiVersion: v1
kind: Pod
metadata:
  name: keycloak-apparmor-dev
  annotations:
    container.apparmor.security.beta.kubernetes.io/hello: localhost/keycloak.profile
spec:
  containers:
  - name: keycloak-profile-dev
    image: busybox
    command: [ "sh", "-c", "echo 'Hello AppArmor!' && sleep 1h" ]
