---
- name: Push AppArmor profile
  hosts: [target_host]
  become: true

  tasks:
    - name: Copy AppArmor profile to target host
      copy:
        content: "{{ lookup('file', 'path/to/profile') }}"
        dest: /etc/apparmor.d/

    - name: Reload AppArmor profiles
      command: apparmor_parser -r /etc/apparmor.d/profile

    - name: Enable AppArmor profile
      command: aa-enforce /etc/apparmor.d/profile

---
- name: Deploy Keycloak AppArmor profile
  hosts: your_target_host
  become: true
  tasks:
    - name: Create AppArmor directory
      file:
        path: /etc/apparmor.d/local/keycloak
        state: directory

    - name: Create AppArmor profile file
      copy:
        src: keycloak.profile
        dest: /etc/apparmor.d/local/keycloak
        mode: 0644

    - name: Reload AppArmor profiles
      shell: /etc/init.d/apparmor reload

    - name: Enforce AppArmor profile
      shell: /sbin/apparmor_parser -e /etc/apparmor.d/local/keycloak

    - name: Restart Keycloak service
      service:
        name: keycloak
        state: restarted